services:
  dockerfile-frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - dockerfile-backend
    restart: always

  dockerfile-backend:
    build:
      context: ./backend
    ports:
      - 4050:4050
    restart: always